#!/bin/zsh

osascript -e '
tell application "Terminal"
    activate
    do script "cd ~/Desktop/MediaApp && eval \"$(/opt/homebrew/bin/brew shellenv zsh)\" 2>/dev/null && set -a && source .env && set +a && source .venv/bin/activate && echo \"\" && echo \"⬡ Emrose Media Studio\" && echo \"  http://localhost:7749\" && echo \"  Press Ctrl+C to stop\" && echo \"\" && (sleep 2 && open http://localhost:7749) & && python -m app.app"
end tell
'
